config/routes.rb
Rails.application.routes.draw do
  resources :plant_details
  root 'plants#index'
  get "/pages/:page" => "pages#show"
  resources :plants
  resources :searches

end

app/models/plant.rb
class Plant < ActiveRecord::Base

  def get_details
    PlantDetail.joins('LEFT OUTER JOIN plants ON plant_details.tsn = plants.tsn').where('plants.tsn = ?', self.tsn)
  end
end

app/models/plant_detail.rb
class PlantDetail < ActiveRecord::Base
end

app/models/search.rb
class Search < ActiveRecord::Base

  def search_plants
    plants = Plant.all
    #plants = plants.where(["name LIKE ?","%#{name}%"]) if name.present?
    column_names.each do |var|
      plants = plants.where(["#{var} LIKE ?","%#{eval(var)}%"]) if eval(var).present?
    end
    plants
  end

  def column_names
    [:name, :leaf_type, :leaf_attachment, :leaf_arrangement, :leaf_veins, :leaf_edge,
     :flower_type, :flower_attachment, :flower_arrangement, :flower_symmetry, :flower_petal_number,
     :flower_petal_color, :fruit_type, :fruit_attachment, :fruit_arrangement, :fruit_color,
     :bark_attachment, :bark_texture, :bark_color, :thorn_type, :thorn_arrangement, :thorn_stiffness,
     :tendril_type, :tendril_attachment, :tendril_arrangement].map(&:to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    @plants = Plant.all
    render "/pages/#{params[:page]}"
  end
end

app/controllers/plant_details_controller.rb
class PlantDetailsController < ApplicationController
  before_action :set_plant_detail, only: [:show, :edit, :update, :destroy]

  # GET /plant_details
  # GET /plant_details.json
  def index
    @plant_details = PlantDetail.all
  end

  # GET /plant_details/1
  # GET /plant_details/1.json
  def show
  end

  # GET /plant_details/new
  def new
    @plant_detail = PlantDetail.new
  end

  # GET /plant_details/1/edit
  def edit
  end

  # POST /plant_details
  # POST /plant_details.json
  def create
    @plant_detail = PlantDetail.new(plant_detail_params)

    respond_to do |format|
      if @plant_detail.save
        format.html { redirect_to @plant_detail, notice: 'Plant detail was successfully created.' }
        format.json { render :show, status: :created, location: @plant_detail }
      else
        format.html { render :new }
        format.json { render json: @plant_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plant_details/1
  # PATCH/PUT /plant_details/1.json
  def update
    respond_to do |format|
      if @plant_detail.update(plant_detail_params)
        format.html { redirect_to @plant_detail, notice: 'Plant detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant_detail }
      else
        format.html { render :edit }
        format.json { render json: @plant_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plant_details/1
  # DELETE /plant_details/1.json
  def destroy
    @plant_detail.destroy
    respond_to do |format|
      format.html { redirect_to plant_details_url, notice: 'Plant detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant_detail
      @plant_detail = PlantDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_detail_params
      params.require(:plant_detail).permit(:tsn, :common_name, :native, :invasive, :typical_habitat, :typical_flowering_time, :typical_fruiting_time, :growth_habit, :annual_biennial_perennial, :toxicity, :medical_uses, :culinary_uses, :ornamental_uses, :other_uses, :status_local, :status_state, :status_us, :status_global, :ecr, :hhcp, :leb, :uwb, :wsp, :ar)
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params.require(:plant).permit(:name, :leaf_type, :leaf_attachment, :leaf_arrangement, :leaf_veins, :leaf_edge, :flower_type, :flower_attachment, :flower_arrangement, :flower_symmetry, :flower_petal_number, :flower_petal_color, :fruit_type, :fruit_attachment, :fruit_arrangement, :fruit_color, :bark_attachment, :bark_texture, :bark_color, :thorn_type, :thorn_arrangement, :thorn_stiffness, :tendril_type, :tendril_attachment, :tendril_arrangement, :tsn)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  def show
    @search = Search.find(params[:id])
    @plants = @search.search_plants
  end

  private
  def search_params
      params[:search] ||= {leaf_type: 'empty search' } #prevents error on empty search
      params.require(:search).permit(:name,
      :leaf_type,
      :leaf_attachment,
      :leaf_arrangement,
      :leaf_veins,
      :leaf_edge,
      :flower_type,
      :flower_attachment,
      :flower_arrangement,
      :flower_symmetry,
      :flower_petal_number,
      :flower_petal_color,
      :fruit_type,
      :fruit_attachment,
      :fruit_arrangement,
      :fruit_color,
      :bark_attachment,
      :bark_texture,
      :bark_color,
      :thorn_type,
      :thorn_arrangement,
      :thorn_stiffness,
      :tendril_type,
      :tendril_attachment,
      :tendril_arrangement,
      :tsn)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plant_details_helper.rb
module PlantDetailsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wild Plant App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/acknowledgements.html.erb
<h1>Acknowledgements</h1>
<p class="pages_back"><%=link_to 'Back', :back %></p>

app/views/pages/contact_us.html.erb
<h1>Contact Us</h1>
<p class="pages_back"><%=link_to 'Back', :back %></p>

app/views/pages/ethics.html.erb
<h1>Ethics</h1>
<p class="pages_back"><%=link_to 'Back', :back %></p>

app/views/pages/glossary.html.erb
<h1>Glossary</h1>
<p style="text-align:center;"><%=link_to 'Back', plants_path, class: 'pages_back' %></p>

app/views/pages/instructions.html.erb
<h1>Instructions</h1>

<div class="list-group">
  <a href="/pages/read_first" class="list-group-item">Read first</a>
  <a href="/pages/ethics" class="list-group-item">Ethics</a>
  <a href="/pages/references" class="list-group-item">References</a>
  <a href="/pages/links" class="list-group-item">Links</a>
  <a href="/pages/acknowledgements" class="list-group-item">Acknowledgements</a>
  <a href="/pages/contact_us" class="list-group-item">Contact Us</a>
</div>

<p class="pages_back"><%=link_to 'Back', plants_path, class: 'pages_back' %></p>

app/views/pages/links.html.erb
<h1>Links</h1>
<p class="pages_back"><%=link_to 'Back', :back %></p>

app/views/pages/map.html.erb
<h1>Map</h1>
<p><%=link_to 'Back', plants_path, class: 'pages_back' %></p>

app/views/pages/plant_listing.html.erb
<h1>Plant Listing</h1>
<p><%=link_to 'Back', plants_path, class: 'pages_back' %></p>

<table class="table table-bordered table-hover table-condensed table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Leaf type</th>
      <th>Leaf attachment</th>
      <th>Leaf arrangement</th>
      <th>Leaf veins</th>
      <th>Leaf edge</th>
      <th>Flower type</th>
      <th>Flower attachment</th>
      <th>Flower arrangement</th>
      <th>Flower symmetry</th>
      <th>Flower petal number</th>
      <th>Flower petal color</th>
      <th>Fruit type</th>
      <th>Fruit attachment</th>
      <th>Fruit arrangement</th>
      <th>Fruit color</th>
      <th>Bark attachment</th>
      <th>Bark texture</th>
      <th>Bark color</th>
      <th>Thorn type</th>
      <th>Thorn arrangement</th>
      <th>Thorn stiffness</th>
      <th>Tendril type</th>
      <th>Tendril attachment</th>
      <th>Tendril arrangement</th>
      <th>Tsn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.name %></td>
        <td><%= plant.leaf_type %></td>
        <td><%= plant.leaf_attachment %></td>
        <td><%= plant.leaf_arrangement %></td>
        <td><%= plant.leaf_veins %></td>
        <td><%= plant.leaf_edge %></td>
        <td><%= plant.flower_type %></td>
        <td><%= plant.flower_attachment %></td>
        <td><%= plant.flower_arrangement %></td>
        <td><%= plant.flower_symmetry %></td>
        <td><%= plant.flower_petal_number %></td>
        <td><%= plant.flower_petal_color %></td>
        <td><%= plant.fruit_type %></td>
        <td><%= plant.fruit_attachment %></td>
        <td><%= plant.fruit_arrangement %></td>
        <td><%= plant.fruit_color %></td>
        <td><%= plant.bark_attachment %></td>
        <td><%= plant.bark_texture %></td>
        <td><%= plant.bark_color %></td>
        <td><%= plant.thorn_type %></td>
        <td><%= plant.thorn_arrangement %></td>
        <td><%= plant.thorn_stiffness %></td>
        <td><%= plant.tendril_type %></td>
        <td><%= plant.tendril_attachment %></td>
        <td><%= plant.tendril_arrangement %></td>
        <td><%= plant.tsn %></td>
      <!--
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/references.html.erb
<h1>References</h1>
<p class="pages_back"><%=link_to 'Back', :back , class: 'pages_back' %></p>

app/views/plant_details/edit.html.erb
<h1>Editing Plant Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @plant_detail %> |
<%= link_to 'Back', plant_details_path %>

app/views/plant_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Plant Details</h1>

<table>
  <thead>
    <tr>
      <th>Tsn</th>
      <th>Common name</th>
      <th>Native</th>
      <th>Invasive</th>
      <th>Typical habitat</th>
      <th>Typical flowering time</th>
      <th>Typical fruiting time</th>
      <th>Growth habit</th>
      <th>Annual biennial perennial</th>
      <th>Toxicity</th>
      <th>Medical uses</th>
      <th>Culinary uses</th>
      <th>Ornamental uses</th>
      <th>Other uses</th>
      <th>Status local</th>
      <th>Status state</th>
      <th>Status us</th>
      <th>Status global</th>
      <th>Ecr</th>
      <th>Hhcp</th>
      <th>Leb</th>
      <th>Uwb</th>
      <th>Wsp</th>
      <th>Ar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plant_details.each do |plant_detail| %>
      <tr>
        <td><%= plant_detail.tsn %></td>
        <td><%= plant_detail.common_name %></td>
        <td><%= plant_detail.native %></td>
        <td><%= plant_detail.invasive %></td>
        <td><%= plant_detail.typical_habitat %></td>
        <td><%= plant_detail.typical_flowering_time %></td>
        <td><%= plant_detail.typical_fruiting_time %></td>
        <td><%= plant_detail.growth_habit %></td>
        <td><%= plant_detail.annual_biennial_perennial %></td>
        <td><%= plant_detail.toxicity %></td>
        <td><%= plant_detail.medical_uses %></td>
        <td><%= plant_detail.culinary_uses %></td>
        <td><%= plant_detail.ornamental_uses %></td>
        <td><%= plant_detail.other_uses %></td>
        <td><%= plant_detail.status_local %></td>
        <td><%= plant_detail.status_state %></td>
        <td><%= plant_detail.status_us %></td>
        <td><%= plant_detail.status_global %></td>
        <td><%= plant_detail.ecr %></td>
        <td><%= plant_detail.hhcp %></td>
        <td><%= plant_detail.leb %></td>
        <td><%= plant_detail.uwb %></td>
        <td><%= plant_detail.wsp %></td>
        <td><%= plant_detail.ar %></td>
        <td><%= link_to 'Show', plant_detail %></td>
        <td><%= link_to 'Edit', edit_plant_detail_path(plant_detail) %></td>
        <td><%= link_to 'Destroy', plant_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plant detail', new_plant_detail_path %>

app/views/plant_details/new.html.erb
<h1>New Plant Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', plant_details_path %>

app/views/plant_details/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Plant Details</h1>
<div class="container">
  <p class="pages_back"><%= link_to 'Back', :back %></p>

  <p>
    <strong>Tsn:</strong>
    <%= @plant_detail.tsn %>
  </p>

  <p>
    <strong>Common name:</strong>
    <%= @plant_detail.common_name %>
  </p>

  <p>
    <strong>Native:</strong>
    <%= @plant_detail.native %>
  </p>

  <p>
    <strong>Invasive:</strong>
    <%= @plant_detail.invasive %>
  </p>

  <p>
    <strong>Typical habitat:</strong>
    <%= @plant_detail.typical_habitat %>
  </p>

  <p>
    <strong>Typical flowering time:</strong>
    <%= @plant_detail.typical_flowering_time %>
  </p>

  <p>
    <strong>Typical fruiting time:</strong>
    <%= @plant_detail.typical_fruiting_time %>
  </p>

  <p>
    <strong>Growth habit:</strong>
    <%= @plant_detail.growth_habit %>
  </p>

  <p>
    <strong>Annual biennial perennial:</strong>
    <%= @plant_detail.annual_biennial_perennial %>
  </p>

  <p>
    <strong>Toxicity:</strong>
    <%= @plant_detail.toxicity %>
  </p>

  <p>
    <strong>Medical uses:</strong>
    <%= @plant_detail.medical_uses %>
  </p>

  <p>
    <strong>Culinary uses:</strong>
    <%= @plant_detail.culinary_uses %>
  </p>

  <p>
    <strong>Ornamental uses:</strong>
    <%= @plant_detail.ornamental_uses %>
  </p>

  <p>
    <strong>Other uses:</strong>
    <%= @plant_detail.other_uses %>
  </p>

  <p>
    <strong>Status local:</strong>
    <%= @plant_detail.status_local %>
  </p>

  <p>
    <strong>Status state:</strong>
    <%= @plant_detail.status_state %>
  </p>

  <p>
    <strong>Status us:</strong>
    <%= @plant_detail.status_us %>
  </p>

  <p>
    <strong>Status global:</strong>
    <%= @plant_detail.status_global %>
  </p>

  <p>
    <strong>Ecr:</strong>
    <%= @plant_detail.ecr %>
  </p>

  <p>
    <strong>Hhcp:</strong>
    <%= @plant_detail.hhcp %>
  </p>

  <p>
    <strong>Leb:</strong>
    <%= @plant_detail.leb %>
  </p>

  <p>
    <strong>Uwb:</strong>
    <%= @plant_detail.uwb %>
  </p>

  <p>
    <strong>Wsp:</strong>
    <%= @plant_detail.wsp %>
  </p>

  <p>
    <strong>Ar:</strong>
    <%= @plant_detail.ar %>
  </p>
</div>

<!--
<%= link_to 'Edit', edit_plant_detail_path(@plant_detail) %> |
<%= link_to 'Back', plant_details_path %>
-->

app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form' %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wild Plant ID</h1>
<p id="subtitle">Identify over 500 different wild plants!</p>
<div class="list-group">
  <a class="list-group-item" href="/pages/instructions">Instructions</a>
  <a class="list-group-item" href="/pages/glossary">Glossary</a>
  <a class="list-group-item" href="/pages/map">Map</a>
  <a class="list-group-item" href="/pages/plant_listing">Plant Listing</a>
  <%= link_to 'Start New Plant ID', new_search_path, class: "list-group-item" %>
</div>

app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form' %>

<%= link_to 'Back', plants_path %>

app/views/plants/plant_listing.html.erb
<h1>Plant Listing</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Leaf type</th>
      <th>Leaf attachment</th>
      <th>Leaf arrangement</th>
      <th>Leaf veins</th>
      <th>Leaf edge</th>
      <th>Flower type</th>
      <th>Flower attachment</th>
      <th>Flower arrangement</th>
      <th>Flower symmetry</th>
      <th>Flower petal number</th>
      <th>Flower petal color</th>
      <th>Fruit type</th>
      <th>Fruit attachment</th>
      <th>Fruit arrangement</th>
      <th>Fruit color</th>
      <th>Bark attachment</th>
      <th>Bark texture</th>
      <th>Bark color</th>
      <th>Thorn type</th>
      <th>Thorn arrangement</th>
      <th>Thorn stiffness</th>
      <th>Tendril type</th>
      <th>Tendril attachment</th>
      <th>Tendril arrangement</th>
      <th>Tsn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.name %></td>
        <td><%= plant.leaf_type %></td>
        <td><%= plant.leaf_attachment %></td>
        <td><%= plant.leaf_arrangement %></td>
        <td><%= plant.leaf_veins %></td>
        <td><%= plant.leaf_edge %></td>
        <td><%= plant.flower_type %></td>
        <td><%= plant.flower_attachment %></td>
        <td><%= plant.flower_arrangement %></td>
        <td><%= plant.flower_symmetry %></td>
        <td><%= plant.flower_petal_number %></td>
        <td><%= plant.flower_petal_color %></td>
        <td><%= plant.fruit_type %></td>
        <td><%= plant.fruit_attachment %></td>
        <td><%= plant.fruit_arrangement %></td>
        <td><%= plant.fruit_color %></td>
        <td><%= plant.bark_attachment %></td>
        <td><%= plant.bark_texture %></td>
        <td><%= plant.bark_color %></td>
        <td><%= plant.thorn_type %></td>
        <td><%= plant.thorn_arrangement %></td>
        <td><%= plant.thorn_stiffness %></td>
        <td><%= plant.tendril_type %></td>
        <td><%= plant.tendril_attachment %></td>
        <td><%= plant.tendril_arrangement %></td>
        <td><%= plant.tsn %></td>
      <!--
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plant.name %>
</p>

<p>
  <strong>Leaf type:</strong>
  <%= @plant.leaf_type %>
</p>

<p>
  <strong>Leaf attachment:</strong>
  <%= @plant.leaf_attachment %>
</p>

<p>
  <strong>Leaf arrangement:</strong>
  <%= @plant.leaf_arrangement %>
</p>

<p>
  <strong>Leaf veins:</strong>
  <%= @plant.leaf_veins %>
</p>

<p>
  <strong>Leaf edge:</strong>
  <%= @plant.leaf_edge %>
</p>

<p>
  <strong>Flower type:</strong>
  <%= @plant.flower_type %>
</p>

<p>
  <strong>Flower attachment:</strong>
  <%= @plant.flower_attachment %>
</p>

<p>
  <strong>Flower arrangement:</strong>
  <%= @plant.flower_arrangement %>
</p>

<p>
  <strong>Flower symmetry:</strong>
  <%= @plant.flower_symmetry %>
</p>

<p>
  <strong>Flower petal number:</strong>
  <%= @plant.flower_petal_number %>
</p>

<p>
  <strong>Flower petal color:</strong>
  <%= @plant.flower_petal_color %>
</p>

<p>
  <strong>Fruit type:</strong>
  <%= @plant.fruit_type %>
</p>

<p>
  <strong>Fruit attachment:</strong>
  <%= @plant.fruit_attachment %>
</p>

<p>
  <strong>Fruit arrangement:</strong>
  <%= @plant.fruit_arrangement %>
</p>

<p>
  <strong>Fruit color:</strong>
  <%= @plant.fruit_color %>
</p>

<p>
  <strong>Bark attachment:</strong>
  <%= @plant.bark_attachment %>
</p>

<p>
  <strong>Bark texture:</strong>
  <%= @plant.bark_texture %>
</p>

<p>
  <strong>Bark color:</strong>
  <%= @plant.bark_color %>
</p>

<p>
  <strong>Thorn type:</strong>
  <%= @plant.thorn_type %>
</p>

<p>
  <strong>Thorn arrangement:</strong>
  <%= @plant.thorn_arrangement %>
</p>

<p>
  <strong>Thorn stiffness:</strong>
  <%= @plant.thorn_stiffness %>
</p>

<p>
  <strong>Tendril type:</strong>
  <%= @plant.tendril_type %>
</p>

<p>
  <strong>Tendril attachment:</strong>
  <%= @plant.tendril_attachment %>
</p>

<p>
  <strong>Tendril arrangement:</strong>
  <%= @plant.tendril_arrangement %>
</p>

<p>
  <strong>Tsn:</strong>
  <%= @plant.tsn %>
</p>

<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>

app/views/searches/new.html.erb
<%= javascript_include_tag 'multistep' %>
<h1>Features</h1>

<!-- having the <p> nested causes text to disappear on hover, but getting
rid of p's causes logic issues with jQuery
may want to just get rid of scaffold css altogether -->

<div class="list-group" id="features">
  <a href="#" class="list-group-item">Leaves</a>
  <a href="#" class="list-group-item">Flowers</a>
  <a href="#" class="list-group-item">Fruit</a>
  <a href="#" class="list-group-item">Bark</a>
  <a href="#" class="list-group-item">Thorns</a>
  <a href="#" class="list-group-item">Tendril</a>
</div>

  <%=form_for @search do |s|%>
    <div class="features">
        <span> <%= render 'leaves', :s => s %> </span>
        <span> <%= render 'flowers', :s => s %> </span>
        <span> <%= render 'fruit', :s => s %> </span>
        <span> <%= render 'bark', :s => s %> </span>
        <span> <%= render 'thorns', :s => s %> </span>
        <span> <%= render 'tendril', :s => s %> </span>
    </div>

    <div class="action">
      <%=s.submit "Search", class: "btn btn-primary" %>
    </div>
  <%end%>

<div class="buttons">
    <button id="first_back" class="btn btn-primary">Back</button>
    <button id="back" class="btn btn-primary">Back</button>
    <button id="next" class="btn btn-primary">Next</button>
    <button id="finish" class="btn btn-primary">Finish</button>
</div>

<div class="back_to_menu">
  <%=link_to 'Back to Menu', plants_path %>
</div>
<!--<p><%=link_to 'Back', plants_path %></p>-->

app/views/searches/show.html.erb
<h1>Search Results</h1>

<%if @plants.empty?%>
  <p style="text-align:center;">No records found</p>
  <div style="text-align:center;"><%=link_to 'New Search', new_search_path, class: 'back_to_search' %></div>
<%else%>
  <p style="text-align:center;"><%=pluralize(@plants.length, "result")%> found.</p>
  <div style="text-align:center;"><%=link_to 'New Search', new_search_path, class: 'back_to_search' %></div>
  <div class="results_table">
    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Tsn</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% i=0 %>
        <% @plants.each do |plant| %>
          <% i+=1 %>
          <tr>
            <td><%= i %></td>
            <!--<td><a href="#"><%=plant.name%></a></td>-->
            <td><%=link_to "#{plant.name}", plant_detail_path(plant.get_details.first.id), class: 'result_link' %></td>
            <td><%=plant.tsn%></td>
          </tr>
        <%end%>
      </tbody>

    </table>
  </div>
<%end%>